const jokes = [
  ["Why don't scientists trust atoms?", "Because they make up everything!"],
  ["What do you call a fake noodle?", "An impasta!"],
  ["Why did the scarecrow win an award?", "He was outstanding in his field!"],
  ["I told my wife she was drawing her eyebrows too high.", "She looked surprised."],
  ["What do you call a bear with no teeth?", "A gummy bear!"],
  ["Why don't eggs tell jokes?", "They'd crack each other up!"],
  ["I'm reading a book about anti-gravity.", "It's impossible to put down!"],
  ["What did the ocean say to the beach?", "Nothing, it just waved."],
  ["Why did the bicycle fall over?", "Because it was two-tired!"],
  ["What do you call cheese that isn't yours?", "Nacho cheese!"],
  ["How does a penguin build its house?", "Igloos it together!"],
  ["Why couldn't the leopard play hide and seek?", "Because he was always spotted!"],
  ["I used to hate facial hair...", "But then it grew on me."],
  ["What did the grape do when it got stepped on?", "Nothing, it just let out a little wine."],
  ["Why do cows have hooves instead of feet?", "Because they lactose!"],
  ["What do you call a dog that does magic?", "A Labracadabrador!"],
  ["I would tell you a construction joke...", "But I'm still working on it."],
  ["Why did the math book look so sad?", "Because it had too many problems."],
  ["What do you call a sleeping dinosaur?", "A dino-snore!"],
  ["I told a chemistry joke once.", "There was no reaction."],
  ["Why do fathers take an extra pair of socks when they go golfing?", "In case they get a hole in one!"],
  ["What did the coffee report to the police?", "A mugging."],
  ["How do you organize a space party?", "You planet."],
  ["What do you call a belt made of watches?", "A waist of time."],
  ["Why can't a nose be 12 inches long?", "Because then it would be a foot."],
  ["I got carded at a liquor store and my Blockbuster card accidentally fell out.", "The cashier said never mind."],
  ["What do you call a factory that makes okay products?", "A satisfactory."],
  ["What did the janitor say when he jumped out of the closet?", "Supplies!"],
  ["Why do dads feel the need to tell such bad jokes?", "They just want to help you become a groan up."],
  ["I used to play piano by ear.", "Now I use my hands."],
  ["What has more letters than the alphabet?", "The post office."],
  ["How do you follow Will Smith in the snow?", "You follow the fresh prints."],
  ["What do you call a fish without eyes?", "A fsh."],
  ["I don't trust stairs.", "They're always up to something."],
  ["What did one wall say to the other?", "I'll meet you at the corner."],
  ["Why don't skeletons ever go trick-or-treating?", "They have no body to go with."],
  ["What do sprinters eat before a race?", "Nothing, they fast."],
  ["I asked my dog what's two minus two.", "He said nothing."],
  ["What's the best thing about Switzerland?", "I don't know, but the flag is a big plus."],
  ["I'm on a seafood diet.", "I see food and I eat it."],
  ["Why do bees have sticky hair?", "Because they use honeycombs."],
  ["What do you call a man with a rubber toe?", "Roberto."],
  ["How does Moses make his coffee?", "Hebrews it."],
  ["What kind of shoes do ninjas wear?", "Sneakers."],
  ["Why did the golfer bring two pairs of pants?", "In case he got a hole in one."],
  ["I wouldn't buy anything with velcro.", "It's a total rip-off."],
  ["What's brown and sticky?", "A stick."],
  ["Why can't you hear a pterodactyl going to the bathroom?", "Because the P is silent."],
  ["What do you call an elephant that doesn't matter?", "An irrelephant."],
  ["Did you hear about the claustrophobic astronaut?", "He just needed a little space."],
  ["What did the buffalo say when his son left for college?", "Bison."],
  ["I just got hit by a rented car.", "It Hertz."],
  ["How do you make a tissue dance?", "Put a little boogie in it."],
  ["Why did the stadium get hot after the game?", "All the fans left."],
  ["What do you call a pig that does karate?", "A pork chop."],
  ["I'm afraid for the calendar.", "Its days are numbered."],
  ["Why did the man fall down the well?", "Because he couldn't see that well."],
  ["When does a joke become a dad joke?", "When it becomes apparent."],
  ["I used to be addicted to the hokey pokey.", "Then I turned myself around."],
  ["What concert costs only 45 cents?", "50 Cent featuring Nickelback."],
  ["Why do melons have weddings?", "Because they cantaloupe."],
  ["What do you call a boomerang that won't come back?", "A stick."],
  ["Why did the tomato turn red?", "Because it saw the salad dressing."],
  ["What do you call a lazy kangaroo?", "A pouch potato."],
  ["I used to be a banker.", "But I lost interest."],
  ["What do you call a snowman with a six-pack?", "An abdominal snowman."],
  ["How do trees access the internet?", "They log in."],
  ["What did the left eye say to the right eye?", "Between us, something smells."],
  ["Why did the picture go to jail?", "Because it was framed."],
  ["What do you call a can opener that doesn't work?", "A can't opener."],
  ["I'm terrified of elevators.", "I'm going to start taking steps to avoid them."],
  ["What do you call a line of rabbits walking backwards?", "A receding hare-line."],
  ["Why couldn't the bicycle stand up by itself?", "It was two-tired."],
  ["What did the duck say when it bought lipstick?", "Put it on my bill."],
  ["I have a joke about time travel.", "But I'm not gonna share it. You guys didn't like it."],
  ["What do you call a hippie's wife?", "Mississippi."],
  ["Why are elevator jokes so good?", "They work on many levels."],
  ["What did one hat say to the other?", "Stay here, I'm going on ahead."],
  ["Why do seagulls fly over the ocean?", "Because if they flew over the bay, they'd be bagels."],
  ["What do you call a deer with no eyes?", "No idea."],
  ["What do you call a deer with no eyes and no legs?", "Still no idea."],
  ["How do you catch a squirrel?", "Climb a tree and act like a nut."],
  ["What sits at the bottom of the sea and twitches?", "A nervous wreck."],
  ["Why do chicken coops only have two doors?", "Because if they had four, they'd be chicken sedans."],
  ["What do you call a pony with a cough?", "A little hoarse."],
  ["What's orange and sounds like a parrot?", "A carrot."],
  ["Did you hear about the guy who invented the knock-knock joke?", "He won the no-bell prize."],
  ["Why don't oysters share their pearls?", "Because they're shellfish."],
  ["I just watched a documentary about beavers.", "It was the best dam show I ever saw."],
  ["What do you call an alligator in a vest?", "An investigator."],
  ["How do you make holy water?", "You boil the hell out of it."],
  ["What did the pirate say on his 80th birthday?", "Aye matey!"],
  ["Why did the coach go to the bank?", "To get his quarterback."],
  ["What's a ninja's favorite type of shoes?", "Sneakers."],
  ["What do you call a sleeping bull?", "A bulldozer."],
  ["I have a joke about paper.", "It's tearable."],
  ["What do lawyers wear to court?", "Lawsuits."],
  ["What do you call a cow with no legs?", "Ground beef."],
  ["What do you call a cow with two legs?", "Lean beef."],
  ["Why did the invisible man turn down the job offer?", "He couldn't see himself doing it."],
  ["What did the mountain climber name his son?", "Cliff."],
  ["I have a fear of speed bumps.", "But I'm slowly getting over it."],
  ["What's a balloon's least favorite type of music?", "Pop."],
  ["Why did the Oreo go to the dentist?", "Because it lost its filling."],
  ["What do you call a toothless bear?", "A gummy bear."],
  ["What did the zero say to the eight?", "Nice belt!"],
  ["Why do fathers take naps on the couch?", "Because they're so good at dad resting."],
  ["How do you make an octopus laugh?", "With ten-tickles."],
  ["What kind of car does an egg drive?", "A Yolkswagen."],
  ["Why did the melon jump into the lake?", "It wanted to be a watermelon."],
  ["I used to work in a shoe recycling shop.", "It was sole destroying."],
  ["What do you call a dinosaur that crashes their car?", "Tyrannosaurus wrecks."],
  ["Why can't you give Elsa a balloon?", "Because she'll let it go."],
  ["What did the policeman say to his belly button?", "You're under a vest."],
  ["I've got a great joke about construction.", "I'm still working on it."],
  ["What do you call a magic dog?", "A Labracadabrador."],
  ["What's the difference between a poorly dressed man on a trampoline and a well-dressed man on a trampoline?", "Attire."],
  ["What do dentists call their x-rays?", "Tooth pics."],
  ["Did you hear about the power outlet who got arrested?", "He was charged with battery."],
  ["What do you call birds that stick together?", "Vel-crows."],
  ["Why couldn't the pony sing?", "Because she was a little horse."],
  ["What did the clock do when it was hungry?", "It went back four seconds."],
  ["Why do bananas have to put on sunscreen before they go to the beach?", "Because they might peel."],
  ["What has ears but cannot hear?", "A cornfield."],
  ["What did Baby Corn say to Mama Corn?", "Where's Pop Corn?"],
  ["Why did the student eat his homework?", "Because his teacher told him it was a piece of cake."],
  ["What do you call a bear caught in the rain?", "A drizzly bear."],
  ["Why do hamburgers go to the gym?", "To get better buns."],
  ["What's the most detail-oriented ocean?", "The Pacific."],
  ["I asked the librarian if the library had any books about paranoia.", "She whispered, 'They're right behind you!'"],
  ["What did the fisherman say to the magician?", "Pick a cod, any cod."],
  ["Why don't scientists trust atoms?", "Because they literally make up everything."],
  ["What did the hat say to the scarf?", "You hang around, I'll go on ahead."],
  ["What do you call a cow during an earthquake?", "A milkshake."],
  ["What do you call a fake stone in Ireland?", "A sham rock."],
  ["How do you organize a space party?", "You planet early."],
  ["Why was the broom late?", "It over-swept."],
  ["What do you call a French guy in sandals?", "Philippe Philoppe."],
  ["Why are spiders so smart?", "They can find everything on the web."],
  ["What do you call a man who can't stand?", "Neil."],
  ["What do you call a woman who can't draw?", "Tracy."],
  ["I have a joke about drilling.", "It's boring."],
  ["Did you hear about the cheese factory explosion?", "There was nothing left but de-brie."],
  ["How do astronomers organize a party?", "They planet."],
  ["What did the green grape say to the purple grape?", "Breathe!"],
  ["What do you get when you cross a snowman with a vampire?", "Frostbite."],
  ["Why do cows wear bells?", "Because their horns don't work."],
  ["What's the difference between a guitar and a fish?", "You can't tuna fish."],
  ["I went to a wedding where two satellite dishes got married.", "The ceremony wasn't much, but the reception was amazing."],
  ["What do you call a group of disorganized cats?", "A cat-astrophe."],
  ["What did the tomato say to the other tomato during a race?", "Ketchup!"],
  ["Why don't ants ever get sick?", "They have little anty-bodies."],
  ["What did one toilet say to the other?", "You look a bit flushed."],
  ["I have a joke about pizza.", "But it's a little cheesy."],
  ["What do you call a country where everyone drives a red car?", "A red car-nation."],
  ["What do elves learn in school?", "The elf-abet."],
  ["Why did the man put his money in the freezer?", "He wanted cold hard cash."],
  ["What do you call two bananas?", "A pair of slippers."],
  ["How do you tell the difference between a bull and a milk cow?", "It's a moot point."],
  ["What did the traffic light say to the car?", "Don't look, I'm about to change."],
  ["Why was the computer cold?", "It left its Windows open."],
  ["I had a dream that I weighed less than a thousandth of a gram.", "I was like, 0mg."],
  ["What do you call a priest who becomes a lawyer?", "A father-in-law."],
  ["What did the calculator say to the student?", "You can count on me."],
  ["How did the barber win the race?", "He took a short cut."],
  ["What do you call a snobbish criminal going downstairs?", "A condescending con descending."],
  ["Why did the gym close down?", "It just didn't work out."],
  ["What do you call a sad cup of coffee?", "A depresso."],
  ["How do you throw a space party?", "You planet."],
  ["Where do fruits go on vacation?", "Pear-is."],
  ["What kind of music do mummies love?", "Wrap music."],
  ["Why was the math teacher suspicious of prime numbers?", "They were just too odd."],
  ["What did the traffic light say to the truck?", "Don't look, I'm changing!"],
  ["I told my daughter she was drawing her eyebrows too high.", "She seemed surprised."],
  ["What kind of tea is the hardest to swallow?", "Reality."],
  ["What do you call a guy lying on the floor?", "Matt."],
  ["What do you call a guy hanging on the wall?", "Art."],
  ["What do you call a guy in a pile of leaves?", "Russell."],
  ["What do you call a guy in a hole?", "Phil."],
  ["What do you call a guy floating in the water?", "Bob."],
  ["What do you call a woman standing on a tennis court?", "Annette."],
  ["Why did the scarecrow become a motivational speaker?", "He was outstanding in his field."],
  ["What's a pirate's favorite letter?", "You think it's R, but his first love be the C."],
  ["Why don't scientists trust stairs?", "Because they're always up to something."],
  ["What do you call a shoe made of a banana?", "A slipper."],
  ["How do you make a water bed bouncier?", "Add spring water."],
  ["What kind of music do planets like?", "Neptunes."],
  ["I used to run a dating service for chickens.", "But I was struggling to make hens meet."],
  ["Why don't eggs ever win arguments?", "They always crack under pressure."],
  ["What did the ocean say to the shore?", "Nothing, it just waved."],
  ["Why was the big cat disqualified from the race?", "Because it was a cheetah."],
  ["What do you call a cow on a trampoline?", "A milkshake."],
  ["Why did the computer go to the doctor?", "It had a virus."],
  ["What do you call a sleeping T-Rex?", "A dino-snore."],
  ["How do you make a lemon drop?", "Just let it fall."],
  ["What did one snowman say to the other?", "Do you smell carrots?"],
  ["Why did the banana go to the doctor?", "It wasn't peeling well."],
  ["What do you call a line of men waiting to get haircuts?", "A barber-queue."],
  ["What do you give a sick lemon?", "Lemon-aid."],
  ["Why did the cookie cry?", "Because its mother was a wafer so long."],
  ["What do you call a broken can opener?", "A can't opener."],
  ["What kind of tree fits in your hand?", "A palm tree."],
  ["Why is Peter Pan always flying?", "Because he Neverlands."],
  ["What did the shark say when he ate the clownfish?", "This tastes a little funny."],
  ["What do you call a singing laptop?", "A Dell."],
  ["Why don't scientists trust the ocean?", "There's something fishy about it."],
  ["How does a scientist freshen her breath?", "With experi-mints."],
  ["What do you call a magician who lost their magic?", "Ian."],
  ["Why did the frog take the bus to work today?", "His car got toad away."],
  ["What do you call a chicken staring at a piece of lettuce?", "Chicken sees a salad."],
  ["How do moths swim?", "Using the butterfly stroke."],
  ["I thought about going on an all-almond diet.", "But that's just nuts."],
  ["What happens when a strawberry gets run over?", "A traffic jam."],
  ["Why did the nurse need a red pen at work?", "In case she needed to draw blood."],
  ["What did the stamp say to the envelope?", "Stick with me and we'll go places."],
  ["Did you hear about the guy who stole a calendar?", "He got 12 months."],
  ["Why don't eggs tell each other jokes?", "They'd crack up."],
  ["How does a taco say grace?", "Lettuce pray."],
  ["What did the fisherman say to the card magician?", "Pick a cod, any cod."],
  ["I've been thinking about taking up meditation.", "I figure it's better than sitting around doing nothing."],
  ["What do you call a donkey with three legs?", "A wonkey."],
  ["I'm writing a book about hurricanes and tornadoes.", "It's only a draft at the moment."],
  ["What do you call a group of killer whales playing instruments?", "An orca-stra."],
  ["Why did the golfer wear two pairs of pants?", "In case he got a hole in one."],
  ["What do you call a peanut in space?", "An astro-nut."],
  ["Why do scuba divers fall backwards off the boat?", "Because if they fell forward, they'd still be in the boat."],
  ["What do you call an apology written in dots and dashes?", "Re-morse code."],
  ["Why did the invisible man turn down a job?", "He just couldn't see himself doing it."],
  ["What's a ghost's favorite dessert?", "I scream."],
  ["I decided to sell my vacuum cleaner.", "All it was doing was gathering dust."],
  ["What do you call a pile of cats?", "A meow-ntain."],
  ["Why did the tree go to the dentist?", "It needed a root canal."],
  ["What's a vampire's favorite fruit?", "A blood orange."],
  ["What do you call a fish that wears a bowtie?", "So-fish-ticated."],
  ["What do you call a rabbit with fleas?", "Bugs Bunny."],
  ["Why do mushrooms get invited to all the parties?", "Because they're fun-gi."],
  ["What do you call an angry carrot?", "A steamed veggie."],
  ["I asked a Frenchman if he played video games.", "He said Wii."],
  ["What's a cat's favorite color?", "Purr-ple."],
  ["Why do math teachers love parks?", "Because of all the natural logs."],
  ["What did the DNA say to the other DNA?", "Do these genes make me look fat?"],
  ["Why was the belt arrested?", "For holding up a pair of pants."],
  ["Where do boats go when they're sick?", "To the dock-tor."],
  ["What lies at the bottom of the ocean and twitches?", "A nervous wreck."],
  ["What do you call a bear with no ears?", "B."],
  ["How does Darth Vader like his toast?", "On the dark side."],
  ["Why was the math book depressed?", "It had too many problems."],
  ["Why did the PowerPoint cross the road?", "To get to the other slide."],
  ["How do you fix a cracked pumpkin?", "With a pumpkin patch."],
  ["What did the roof say to the house?", "I've got you covered."],
  ["Why do moon rocks taste better than earth rocks?", "Because they're a little meteor."],
  ["What do you call someone with no body and no nose?", "Nobody knows."],
  ["What do you call a parade of rabbits hopping backward?", "A receding hare-line."],
  ["Why are ghosts bad liars?", "Because you can see right through them."],
  ["What sits on the seabed and shivers?", "A nervous wreck."],
  ["What do you call a sleeping pizza?", "A piZZZa."],
  ["Why do bicycles fall over?", "Because they are two-tired."],
  ["What do you call a duck that gets all A's?", "A wise quacker."],
  ["Did you hear about the restaurant on the moon?", "Great food, no atmosphere."],
  ["What do cows read in the morning?", "The moos-paper."],
  ["I used to be a personal trainer.", "Then I gave my too weak notice."],
  ["Why did the coffee file a police report?", "It got mugged."],
  ["What do you call a fake Irish diamond?", "A shamrock."],
  ["What goes up and down but doesn't move?", "Stairs."],
  ["I asked my date to meet me at the gym.", "She didn't show up. That's when I knew we weren't going to work out."],
  ["I'm so good at sleeping.", "I can do it with my eyes closed."],
  ["What do you call a cow that just had a baby?", "De-calf-inated."],
  ["Why can't your ear be 12 inches?", "Because then it would be a foot."],
  ["What do you call a man with no arms and no legs in a pool?", "Bob."],
  ["Why did the crab never share?", "Because he's shellfish."],
  ["I told my son I was named after Thomas Jefferson.", "He said, 'But Dad, your name is Brian.' I said, 'I know, but I was named AFTER Thomas Jefferson.'"],
  ["What kind of music do chiropractors listen to?", "Hip pop."],
  ["What do you call a row of rabbits hopping away?", "A receding hare line."],
  ["Did you hear the rumor about butter?", "Well, I'm not going to spread it."],
  ["What do you call a fly without wings?", "A walk."],
  ["I thought about going on an all-almond diet.", "But that's just nuts!"],
  ["Why did the old man fall in the well?", "Because he couldn't see that well."],
  ["What kind of shorts do clouds wear?", "Thunderwear."],
  ["Why was the baby strawberry crying?", "Because her mom and dad were in a jam."],
  ["A cheese factory exploded in France.", "Da brie is everywhere!"],
  ["What do you call a cat sitting on the beach on Christmas Eve?", "Sandy Claws."],
  ["What does a house wear?", "Address."],
  ["Why are piggy banks so wise?", "They're filled with common cents."],
  ["I tried to write a chemistry joke.", "But I got no reaction."],
  ["Why did the scarecrow get a promotion?", "Because he was outstanding in his field!"],
  ["What did one plate say to the other plate?", "Dinner is on me!"],
  ["What did the paper say to the pencil?", "Write on!"],
  ["What do you call a nervous javelin thrower?", "Shakespeare."],
  ["How do you find Will Smith in the snow?", "Just look for fresh prints."],
  ["What does a cloud wear under his raincoat?", "Thunderwear."],
  ["What kind of bagel can fly?", "A plain bagel."],
  ["What did the grape say when it got crushed?", "Nothing, it just let out a little wine."],
  ["I got a reversible jacket for Christmas.", "I can't wait to see how it turns out."],
  ["What do you get from a pampered cow?", "Spoiled milk."],
  ["What did the drummer call his twin daughters?", "Anna one, Anna two!"],
  ["What did the rug say to the floor?", "I've got you covered!"],
  ["What do you get when you cross a vampire with a snowman?", "Frostbite!"],
  ["Why do dads always carry a spare joke?", "In case the first one doesn't land."],
  ["What do you call a snowman in July?", "A puddle."],
  ["Why did the bicycle need a nap?", "It was wheely tired."]
];

function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

let queue = [];
const box = document.getElementById("joke-box");
const btn = document.getElementById("btn");

function nextJoke() {
  if (queue.length === 0) queue = shuffle([...jokes]);
  return queue.pop();
}

btn.addEventListener("click", () => {
  box.classList.remove("visible");
  setTimeout(() => {
    const [setup, punchline] = nextJoke();
    box.innerHTML = `<p>${setup}</p><p style="margin-top:12px;font-weight:700">${punchline}</p>`;
    box.classList.add("visible");
  }, 200);
});
